### ISSUE TITLE
AppScan version?

### ISSUE THREAD

**Issue by blairdrummond** [Bruk0ut/appscan-xml-report-parser#1]
Hi @Bruk0ut , do you know whether this was run on the Standard or Enterprise version of AppScan?

(And by any chance, do you have a sample XML file?)

**Comment by Bruk0ut** [comment]
@blairdrummond it was developed and tested using the Standard version of AppScan (9.0.3.7 exclusively). I don't have any XML scan files that I can share, but I referenced the CLI arguments required to launch a new scan and save to XML in the opening comments of the Python Script.

```
Notes: To generate an AppScan XML report from fresh scan -> AppScanCMD.exe e /su http://host/ /rf path_to_output_xml_file.xml /rtm DetailedReport /rt xml /v
Notes: To generate an AppScan XML report from existing `.scan` file -> AppScanCMD.exe report /base_scan path_to_.scan_file.scan -report_file path_to_output_xml_file.xml /report_type xml
```
Hope that helps

--Bruk0ut
