### ISSUE TITLE
Error - could not parse summary stats from xml report?

### ISSUE THREAD

**Issue by EkramulHoque** [Bruk0ut/appscan-xml-report-parser#2]
Hi @Bruk0ut ,

I have been trying to convert this scan report, the version is **9.0.3.12**:

https://github.com/DefectDojo/sample-scan-files/blob/master/appscan/ibm_appscan_xml_file.xml

does the parser supports this version? or is it have to **9.0.3.7**?

Thanks

**Comment by Bruk0ut** [comment]
@EkramulHoque The parser was only tested on 9.0.3.7 Standard and there is no further support, sorry.
--Bruk0ut
